ALTER TABLE public.crt_lancamentos
  ADD COLUMN IF NOT EXISTS substituto TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS substituto_person_id TEXT,
  ADD COLUMN IF NOT EXISTS recebeu_vt TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS recebeu_refeicao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS valor_receber TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS recebido_em DATE;